### List
GET http://localhost:8000/api/autores

### Create
POST http://localhost:8000/api/autores
Content-Type: application/json

{
    "id": 2,
    "nome": "beltrano",
    "email": "beltrano@teste.com.br",
    "senha": "4321"
}

### Find
GET http://localhost:8000/api/autores/1


### Update
PUT http://localhost:8000/api/autores/2
Content-Type: application/json

{
    "id": 2,
    "nome": "ciclano",
    "email": "ciclano@teste.com.br",
    "senha": "1243"
}


### Delete
DELETE http://localhost:8000/api/autores/2


### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "login": "rafael",
    "senha": "1234"
}


### Timeline
GET http://localhost:8000/api/fotos
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InJhZmFlbCIsImlhdCI6MTU2NzUxNjY5NCwiZXhwIjoxNTY3NTIwMjk0fQ.4m4815TyuNsHA__VvE77E1U26WeGVD_JH_Qh6ESqexw